// <auto-generated />
using System;
using InsertKph.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsertKph.Migrations
{
    [DbContext(typeof(MyWorldDbContext))]
    partial class MyWorldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsertKph.Models.IpdProgressNote", b =>
                {
                    b.Property<int>("progress_note_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("progress_note_id"));

                    b.Property<string>("an")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("pre_order_progress_note_date")
                        .HasColumnType("date");

                    b.Property<int?>("pre_order_progress_note_id")
                        .HasColumnType("int");

                    b.Property<string>("pre_order_progress_note_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("progress_note_date")
                        .HasColumnType("date");

                    b.Property<string>("progress_note_doctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("progress_note_enter_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("progress_note_owner_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progress_note_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("progress_note_id");

                    b.ToTable("IpdProgressNote");
                });

            modelBuilder.Entity("InsertKph.Models.IpdProgressNoteItem", b =>
                {
                    b.Property<int>("progress_note_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("progress_note_item_id"));

                    b.Property<string>("an")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_datetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("progress_note_id")
                        .HasColumnType("int");

                    b.Property<string>("progress_note_item_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progress_note_item_detail2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progress_note_item_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_datetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("progress_note_item_id");

                    b.ToTable("IpdProgressNoteItems");
                });
#pragma warning restore 612, 618
        }
    }
}
